### ISSUE TITLE
Allow users to add their own query in the config file

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/repofetch#19]
In the config file, there could be
```yml
custom output:
  github: # host of repo
    issues: # specifying that below queries are for Search::issues
      queries: 
      - enhancement issues: # text to be displayed before stat
          emoji: "💪" # emoji before stat text
          filters: # what filters to use
          - is: issue
          - label: enhancement
```
